services:
  - type: web
    name: odoo-web
    env: docker
    repo: https://github.com/YamilTorricoVasquez/prueba.git
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: odoo
      - key: DB_PASSWORD
        value: myodoo
      - key: DB_NAME
        value: postgres

  - type: database
    name: odoo-db
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        value: myodoo
      - key: POSTGRES_DB
        value: postgres
    volumes:
      - name: postgres_data
        path: /var/lib/postgresql/data
